# Generated by Django 5.0.4 on 2024-04-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                ("book_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("book_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number_of_copies", models.IntegerField(default=0)),
            ],
        ),
    ]
